import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Auto</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/hoverlogo.svg' />
      </Head>
      <Navbar />

      <div className={styles.main}>MAIN</div>

      <div className={styles.footer}>FOOTER</div>
    </div>
  )
}

export default Home
