import type { NextPage } from 'next'
import Head from 'next/head'
import CityscapeHero from '../components/CityscapeHero'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import TimeFocusHero from '../components/TimeFocusHero'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Auto</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/hoverlogo.svg' />
      </Head>
      <div className={styles.top}>
        <Navbar />
        <CityscapeHero />
      </div>
      <div className={styles.bottom}>
        <TimeFocusHero />
        <Footer />
      </div>
    </div>
  )
}

export default Home
